
for i=1:50
    figure(i)
plot3(X(:,:,i),Z,Y(:,:,i),'--rs','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','g',...
                'MarkerSize',10);
             axis([140 260 5 15 145 170]);
hold on ;
X1=[X(1,1,i) X(1,n,i)];
Y1=[Y(1,1,i) Y(1,n,i)];
Z1=[Z(1,1) Z(1,n)];
plot3(X1,Z1,Y1,'--rs','LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor','g',...
                'MarkerSize',10);
end